// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

/// Reset the parser state. Call before starting a new connection.
void parserReset() => RustLib.instance.api.crateApiSimpleParserReset();

/// Feed raw bytes to the parser and get back a JSON array string of parsed objects.
/// protocol_hint: 0 = AutoDetectStream (NMEA/UBX), 1 = QstarzBleChunk
String parserFeed({required List<int> data, required int protocolHint}) =>
    RustLib.instance.api
        .crateApiSimpleParserFeed(data: data, protocolHint: protocolHint);
